### ISSUE TITLE
Not using configFile and requires full path to ignored files

### ISSUE THREAD

**Issue by mikeerickson** [alleyinteractive/sasslint-webpack-plugin#25]
I have the following (configuration)
- It is NOT using the include/ignore files form `.sass-lint.yml` file
- In order to properly ignore files, I must use the full path (see first entry) where as the format for second entry (yes they are different files, just testing various options).
- The first entry is ignored correctly (notice full path)
- The second entry is NOT ignored

```
    new SassLintPlugin({
      configFile: '.sass-lint.yml',
      ignoreFiles: [
        '/Users/mikeerickson/Documents/Projects/angular-sandbox/src/sass/mixins/text.sass',
        './src/sass/modules/_reset.scss'
      ]
    }),
```

Here is my result when running webpack

```
...
/Users/mikeerickson/Documents/Projects/angular-sandbox/src/sass/modules/_reset.scss
   1:6   warning  Selectors must be placed on new lines                           single-line-per-selector
   1:12  warning  Selectors must be placed on new lines                           single-line-per-selector
...
```

As you can see, the `_reset.scss` file is still being checked, despite its defined ignore item

**Comment by mikeerickson** [comment]
Well, looks like pilot error (for ingnore option).  But still curious about reading files from `.sass-lint.yml` file

From the docs (sorry didn't read this thoroughly)
- `ignoreFiles`: Array of files to ignore, **must be full path**, Default: none

So, the question still remains.  If I have the following in `.sass-lint.yml` file, should plugin use these entires?

```
files:
  include:
    - "./src/sass/**/*.s+(a|c)ss"
  ignore:
    - "./src/sass/disabled/**/*.s+(a|c)ss"
    - "./src/sass/modules/*.s+(a|c)ss"
    - "node_modules/**/*.s+(a|c)ss"
```
